"""new schema

Revision ID: 0045fe0c4ced
Revises: 
Create Date: 2018-04-08 15:43:29.094690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0045fe0c4ced'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('lastfm_tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('tracks', sa.Column('preview_url', sa.String(length=600), nullable=True))
    op.create_index(op.f('ix_tracks_preview_url'), 'tracks', ['preview_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_preview_url'), table_name='tracks')
    op.drop_column('tracks', 'preview_url')
    op.drop_column('tracks', 'lastfm_tags')
    # ### end Alembic commands ###
