"""remove spotify album genres cause its useless

Revision ID: 251ae2fa03f5
Revises: fcc7500d7a4b
Create Date: 2018-04-30 21:05:36.249259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '251ae2fa03f5'
down_revision = 'fcc7500d7a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'spotify_album_genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('spotify_album_genres', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
