"""added order_in_playlist

Revision ID: 86f0c50e3321
Revises: ec7661e46e8e
Create Date: 2018-02-24 18:27:52.631088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f0c50e3321'
down_revision = 'ec7661e46e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_to_track', sa.Column('order_in_playlist', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist_to_track', 'order_in_playlist')
    # ### end Alembic commands ###
