"""added playlist user

Revision ID: b2a04f6b3d35
Revises: cbe82259d53f
Create Date: 2017-12-31 13:41:41.717167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a04f6b3d35'
down_revision = 'cbe82259d53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('playlist_user', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_playlists_playlist_user'), 'playlists', ['playlist_user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlists_playlist_user'), table_name='playlists')
    op.drop_column('playlists', 'playlist_user')
    # ### end Alembic commands ###
