"""added attribute playlists in Track and table names

Revision ID: cbe82259d53f
Revises: 
Create Date: 2017-12-26 19:25:04.300152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe82259d53f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_spotify_id'), 'playlists', ['spotify_id'], unique=True)
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=True),
    sa.Column('musicbrainz_id', sa.String(length=100), nullable=True),
    sa.Column('artist', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_artist'), 'tracks', ['artist'], unique=False)
    op.create_index(op.f('ix_tracks_musicbrainz_id'), 'tracks', ['musicbrainz_id'], unique=True)
    op.create_index(op.f('ix_tracks_name'), 'tracks', ['name'], unique=False)
    op.create_index(op.f('ix_tracks_spotify_id'), 'tracks', ['spotify_id'], unique=True)
    op.create_table('playlist_to_track',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'track_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_to_track')
    op.drop_index(op.f('ix_tracks_spotify_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_name'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_musicbrainz_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_artist'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_playlists_spotify_id'), table_name='playlists')
    op.drop_table('playlists')
    # ### end Alembic commands ###
