"""required columns not nullable

Revision ID: ec7661e46e8e
Revises: a4860ec7676a
Create Date: 2017-12-31 16:22:08.881736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7661e46e8e'
down_revision = 'a4860ec7676a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlists', 'playlist_user',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('playlists', 'spotify_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('tracks', 'artist',
               existing_type=sa.VARCHAR(length=600),
               nullable=False)
    op.alter_column('tracks', 'name',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('tracks', 'spotify_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'spotify_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tracks', 'name',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('tracks', 'artist',
               existing_type=sa.VARCHAR(length=600),
               nullable=True)
    op.alter_column('playlists', 'spotify_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('playlists', 'playlist_user',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
