"""added spotify album and artist genre columns in tracks table

Revision ID: fcc7500d7a4b
Revises: 34384e1f0897
Create Date: 2018-04-30 19:59:33.674771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fcc7500d7a4b'
down_revision = '34384e1f0897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('spotify_album_genres', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('tracks', sa.Column('spotify_artist_genres', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'spotify_artist_genres')
    op.drop_column('tracks', 'spotify_album_genres')
    # ### end Alembic commands ###
